services:
  - type: web
    name: programming-platform
    env: python
    region: frankfurt  # или singapore, oregon, ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers=2 main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    healthCheckPath: /

    autoDeploy: true
